# This pipeline uses the https://woodpecker-ci.org/plugins/Docker%20Buildx plugin

variables:
  - &repo 'docker.io/devture/exim-relay'
  - &dockerfile 'Dockerfile'
  - &platforms 'linux/amd64,linux/arm64/v8,linux/arm/v7'

services:
  docker:
    image: docker:24.0.7-dind
    commands:
      - dockerd --tls=false --host=tcp://0.0.0.0:2376
    privileged: true

steps:
  build-and-push-for-branch:
    when:
      - event: push
        branch: ${CI_REPO_DEFAULT_BRANCH}
      - event: manual
    image: woodpeckerci/plugin-docker-buildx:2.2.1
    environment:
      - DOCKER_HOST=tcp://docker:2376
    secrets: [docker_username, docker_password]
    settings:
      repo: *repo
      tag: latest
      dockerfile: *dockerfile
      platforms: *platforms

  build-and-push-for-tag:
    when:
      - event: tag
    image: woodpeckerci/plugin-docker-buildx:2.2.1
    environment:
      - DOCKER_HOST=tcp://docker:2376
    secrets: [docker_username, docker_password]
    settings:
      repo: *repo
      tag: ${CI_COMMIT_TAG}
      dockerfile: *dockerfile
      platforms: *platforms
