{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "exim.fullname" . }}
  labels:
    app: {{ template "exim.name" . }}
    chart: {{ template "exim.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
{{ toYaml .Values.rbac.role.rules }}
{{- end }}
